stages:
  - build
  - deploy

variables:
  IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_BRANCH}"
  IMAGE_LATEST: "$CI_REGISTRY_IMAGE:swarm"


build-swarm:
  stage: build
  before_script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - echo "$SECRETS_FILE" > config/secrets.yml
  script:
    - docker build -t $IMAGE -t $IMAGE_LATEST -f Dockerfile.prod  .
    - docker push $IMAGE_LATEST
    - docker push $IMAGE
  tags:
    - swarm

.deploy:
  stage: deploy
  script: 
    - echo "$TG_BOT" > tg_bot
    - echo "$TG_DATABASE" > database
    - docker stack deploy -c docker-compose.yml muul
    - docker image prune -af
  tags:
    - swarm

deploy-swarm:
  environment: prod
  extends: .deploy
