version: '3.8'

services:

  tg_bot:
    image: ghcr.io/irinalepekhina/tg_bot:latest
    container_name: tg_bot
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./env/development/database
      - ./env/development/tg_bot
    depends_on:
      - tg_bot_redis
      - ngrok
    networks:
      tg_bot_front:
        aliases:
          - tg_bot
      chat_bot:
        aliases:
          - tg_bot

  tg_bot_redis:
    image: redis/redis-stack:7.2.0-v4
    container_name: tg_bot_redis
    networks:
      tg_bot_front:
        aliases:
          - tg_bot_redis

  tg_bot_db:
    image: postgres:16
    container_name: tg_bot_db
    env_file:
      - ./env/development/database
    volumes:
      - db_data_tg_bot:/var/lib/postgresql/data
    networks:
      tg_bot_front:
        aliases:
          - tg_bot_db

  tg_bot_db_migrator:
    image: ghcr.io/irinalepekhina/tg_bot:latest
    container_name:  tg_bot_db_migrator
    command: ["./wait-for", "--timeout=60", "tg_bot_db:5432", "--",
      "bin/rails", "db:prepare"]
    env_file:
      - ./env/development/database
      - ./env/development/tg_bot
    networks:
      tg_bot_front:
        aliases:
          - tg_bot_db_migrator

  tg_bot_webhook:
    image: ghcr.io/irinalepekhina/tg_bot:latest
    container_name:  tg_bot_webhook
    env_file:
      - ./env/development/database
      - ./env/development/tg_bot
    command: ["./wait-for", "--timeout=90", "tg_bot:3001", "--",
      "bundle", "exec", "rake", "telegram:set_webhook"]
    networks:
      tg_bot_front:
        aliases:
          - tg_bot_webhook
        
  tg_bot_signup:
    image: ghcr.io/irinalepekhina/tg_bot:latest
    container_name:  tg_bot_signup
    command: ["./wait-for", "--timeout=120", "tg_bot:3001", "--",
      "bundle", "exec", "rake", "bot:initialize_user"]
    env_file:
      - ./env/development/database
      - ./env/development/tg_bot
    networks:
      tg_bot_front:
        aliases:
          - tg_bot_signup
      chat_bot:
        aliases:
          - tg_bot_signup

  tg_bot_redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name:  tg_bot_redisinsight
    ports:
      - '8002:8001'
    volumes:
      - redisinsight_data_tg_bot:/db
    networks:
      tg_bot_front:
        aliases:
          - tg_bot_redisinsight

  ngrok:
    image: ngrok/ngrok
    container_name:  ngrok
    env_file:
          - ./env/development/tg_bot
    command: 
      - http
      - "tg_bot:3001"
      - "--domain=awake-javelin-previously.ngrok-free.app"
    ports:
      - "4040:4040"
    networks:
      - tg_bot_front

volumes:
  db_data_tg_bot:
  redisinsight_data_tg_bot:

networks:
  tg_bot_front:
    driver: bridge
    name:   tg_bot_front
  chat_bot:
    external: true