# PostgreSQL. Versions 9.3 and up are supported.

# For details on connection pooling, see Rails configuration guide
# https://guides.rubyonrails.org/configuring.html#database-pooling
# https://guides.rubyonrails.org/configuring.html#configuring-a-database

development:
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  pool: 5
  variables:
    statement_timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: bot_test
  pool: 5
  variables:
    statement_timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  host:     <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  pool: 5
  variables:
    statement_timeout: 5000


# default: &default
#   adapter: postgresql
#   encoding: unicode
#   host:     <%= ENV['DATABASE_HOST'] %>
#   username: <%= ENV['POSTGRES_USER'] %>
#   password: <%= ENV['POSTGRES_PASSWORD'] %>
#   database: <%= ENV['POSTGRES_DB'] %>
#   pool: 5
#   variables:
#     statement_timeout: 5000

# development:
#   <<: *default

# test:
#   <<: *default
#   database: chat_test

# production:
#   <<: *default
